spring:
  jpa:
    database: default
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driverClassName: com.mysql.cj.jdbc.Driver